import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Lalezar } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans bg-gradient-to-r from-[#c6d3e6] to-[#79b4f3]`}
        
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
